# Generated by Django 5.0.6 on 2024-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_type_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
