# Generated by Django 5.0.6 on 2024-07-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_job_type_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_type_temp',
        ),
    ]
